
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  # Sets a port number to use for Home Assistant to use (default 8123).
  server_port: 8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

  ip_ban_enabled: false
  login_attempts_threshold: 5

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
